# Generated by Django 2.1.4 on 2018-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('ultimo_fechamento', models.CharField(max_length=200)),
                ('maxima52semanas', models.CharField(max_length=200)),
                ('minima52semanas', models.CharField(max_length=200)),
                ('qtdnegociado_21dias', models.CharField(max_length=200)),
                ('volume_medio', models.CharField(max_length=200)),
                ('data_json', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'acoes',
            },
        ),
    ]
